CREATE TABLE `product` (
  `id` varchar(32) NOT NULL,
  `AuctionTitle` varchar(80) DEFAULT '',
  `Sku` varchar(50) NOT NULL DEFAULT '',
  `SKUType` varchar(50) DEFAULT '',
  `Quantity` int(11) unsigned DEFAULT '0',
  `QuantityUpdateType` varchar(64) DEFAULT '',
  `DCQuantity` varchar(255) DEFAULT '',
  `DCQuantityUpdateType` varchar(64) DEFAULT 'copletedclist',
  `TotalQuantity` int(11) unsigned DEFAULT '0',
  `QuantityOpen` int(11) unsigned DEFAULT '0',
  `QuantityPendingCheckout` int(11) unsigned DEFAULT '0',
  `QuantityPendingPayment` int(11) unsigned DEFAULT '0',
  `QuantityPendingShipment` int(11) unsigned DEFAULT '0',
  `QuantityPooledOpen` int(11) unsigned DEFAULT '0',
  `QuantityPooledPendingCheckout` int(11) unsigned DEFAULT '0',
  `QuantityPooledPendingPayment` int(11) unsigned DEFAULT '0',
  `QuantityPooledPendingShipment` int(11) unsigned DEFAULT '0',
  `QuantityoneBay` int(11) unsigned DEFAULT '0',
  `QuantityoneBayPooled` int(11) unsigned DEFAULT '0',
  `QuantityonAmazon` int(11) unsigned DEFAULT '0',
  `QuantityonAmazonPooled` int(11) unsigned DEFAULT '0',
  `QuantityonRakutencomShopping` int(11) unsigned DEFAULT '0',
  `QuantityonRakutencomShoppingPooled` int(11) unsigned DEFAULT '0',
  `ItemCreateDate` varchar(32) DEFAULT '',
  `ItemLastModifiedDate` varchar(32) DEFAULT '',
  `StartingBid` double(11,2) DEFAULT '0.00',
  `Reserve` double(11,2) DEFAULT '0.00',
  `Weight` double(11,2) DEFAULT '0.00',
  `ISBN` varchar(20) DEFAULT '',
  `UPC` varchar(20) DEFAULT '',
  `EAN` varchar(20) DEFAULT '',
  `ASIN` varchar(14) DEFAULT '',
  `MPN` varchar(50) DEFAULT '',
  `ShortDescription` varchar(1000) DEFAULT '',
  `Description` varchar(2000) DEFAULT '',
  `Flag` varchar(50) DEFAULT '',
  `FlagDescription` varchar(100) DEFAULT '',
  `Blocked` varchar(8) DEFAULT '',
  `BlockedComment` varchar(100) DEFAULT '',
  `BlockExternalQuantity` varchar(8) DEFAULT '',
  `Manufacturer` varchar(255) DEFAULT '',
  `Brand` varchar(150) DEFAULT '',
  `Condition` varchar(16) DEFAULT '',
  `Warranty` varchar(255) DEFAULT '',
  `SellerCost` double(11,2) DEFAULT '0.00',
  `ProductMargin` double(11,2) DEFAULT '0.00',
  `BuyItNowPrice` double(11,2) DEFAULT '0.00',
  `RetailPrice` double(11,2) DEFAULT '0.00',
  `SecondChanceOfferPrice` double(11,2) DEFAULT '0.00',
  `PictureURLs` text,
  `TaxProductCode` varchar(25) DEFAULT '',
  `SupplierCode` varchar(50) DEFAULT '',
  `SupplierPO` varchar(255) DEFAULT '',
  `WarehouseLocation` varchar(55) DEFAULT '',
  `ReceivedInInventory` varchar(32) DEFAULT '',
  `InventorySubtitle` varchar(100) DEFAULT '',
  `RelationshipName` varchar(50) DEFAULT '',
  `VariationParentSKU` varchar(50) DEFAULT '',
  `Labels` varchar(1000) DEFAULT '',
  `ChannelAdvisorStoreTitle` varchar(100) DEFAULT '',
  `ChannelAdvisorStoreDescription` varchar(2000) DEFAULT '',
  `StoreMetaDescription` varchar(200) DEFAULT '',
  `ChannelAdvisorStorePrice` double(11,2) DEFAULT '0.00',
  `ChannelAdvisorStoreCategoryID` int(11) unsigned DEFAULT 0,
  `ChannelAdvisorStoreCategoryHierarchy` varchar(255) DEFAULT '',
  `ChannelAdvisorStoreCategoryName` varchar(255) DEFAULT '',
  `ChannelAdvisorStoreURL` varchar(255) DEFAULT '',
  `HarmonizedCode` varchar(20) DEFAULT '',
  `Height` double(11,2) DEFAULT '0.00',
  `Length` double(11,2) DEFAULT '0.00',
  `Width` double(11,2) DEFAULT '0.00',
  `Deleted` tinyint(1) DEFAULT 0,
  `Edited` tinyint(1) DEFAULT 0,
  `Created` tinyint(1) DEFAULT 0,
  `CreatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `Sku` (`Sku`) USING BTREE,
  KEY `Manufacturer` (`Manufacturer`) USING BTREE,
  KEY `CreatedAt` (`CreatedAt`) USING BTREE,
  KEY `UpdatedAt` (`UpdatedAt`) USING BTREE,
  KEY `sku_skutype` (`Sku`,`SKUType`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
